apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - newsdata.io
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-newsdata
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: newsdata
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-newsdata-through-egress-gateway
spec:
  hosts:
  - newsdata.io
  gateways:
  - mesh
  - istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - newsdata.io
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: newsdata
        port:
          number: 443
  - match:
    - gateways:
      - istio-egressgateway
      port: 443
      sniHosts:
      - newsdata.io
    route:
    - destination:
        host: newsdata.io
        port:
          number: 443
      weight: 100